### PR TITLE
Fix linking with non framework builds of qt (e.g. from conda-forge)

### PR DESCRIPTION
**Pull request by anton-matosov**
Add auto-detection if qt was built with frameworks option on by probing for QtCore.framework existence
Add renaming of libraries to link from Qt* to Qt5* for darwin if non-framework build is used

### CODE REVIEW

**Comment by anton-matosov** [comment]
👋  @dirk-thomas,
This is my first contribution to ROS and I am not sure what is the process for it.
I have opened several PRs to several ROS packages, but didn't hear anything back on any of them.
What is the regular process for ROS contribution? 
What is the usual turnaround time for pull requests?

**Comment by anton-matosov** [comment]
Hello @dirk-thomas, can you take a look at PR, please?

**Comment by Tobias-Fischer** [comment]
Works perfectly for me!

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Comment by Tobias-Fischer** [comment]
Will this be backported to melodic/noetic?

**Comment by dirk-thomas** [comment]
> Will this be backported to melodic/noetic?

Not automatically. Thanks for bringing it up. Done in 5c2f6d98fda09196dda07248d315411dd45e5f2d.

**Pull request merged**
