### PR TITLE
Suppress warning from Shiboken2.

### PR DESCRIPTION
**Pull request by clalancette**
The comment has more information on why we are doing this.

Fixes https://github.com/ros-visualization/qt_gui_core/issues/291

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20930/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15225/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21608/)

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Comment by Crola1702** [comment]
I'm seeing in RHEL Debug, repeated and packaging:

```
--- stderr: qt_gui_cpp
00:12:27.703 CMake Error at /home/jenkins-agent/workspace/nightly_linux-rhel_debug/ws/install/python_qt_binding/share/python_qt_binding/cmake/shiboken_helper.cmake:27 (cmake_policy):
00:12:27.703   Policy "CMP0148" is not known to this version of CMake.
00:12:27.703 Call Stack (most recent call first):
00:12:27.703   src/qt_gui_cpp_shiboken/CMakeLists.txt:43 (include)
```

**Comment by ahcorde** [comment]
@Crola1702 This PR https://github.com/ros-visualization/python_qt_binding/pull/139 fixed the issue

**Comment by Crola1702** [comment]
Makes sense. Just noticed that the build was run 9h ago. Thanks!

**Pull request merged**
