### PR TITLE
Use PyQt5 module path to find SIP bindings (ROS 2)

### PR DESCRIPTION
**Pull request by lopsided98**
This applies #95 and #105 to the main branch to be included in a ROS 2 release.

### CODE REVIEW

**Review by cottsay — APPROVED** [review]
This worked for me on Fedora 35. Thanks!

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15628/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10309/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13296/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15845/)

**Review by clalancette — APPROVED** [review]
This also works for me on Ubuntu 22.04.  Thanks!

**Comment by clalancette** [comment]
All of the failing tests are in the nightlies as well, so not added by this PR.  I'm going to go ahead and merge this, thanks again.

**Pull request merged**
